### ISSUE TITLE
Please add screenshots

### ISSUE THREAD

**Issue by licht1stein** [pink-gorilla/goldly#35]
Hi! I'm trying to find a tool to use in an existing project, and since goldly is a visualization tool, having a couple screenshots would really, really help. Thanks!

**Comment by awb99** [comment]
Hi! Sorry for the late reply. You can have a look at two projects: goldly-test (in goldly repo), goldly-demo, or clojure-quant/trateg to see how it works. We will add a static-page export function this year that will let you see all the renderers easily. Until then the only way to see vizualisations is to start a project.

**Comment by licht1stein** [comment]
Thanks, I don't even remember any more what I wanted to do. But having a couple of screenshots right in the README wouldn't hurt 🙃
